# -*- coding: utf-8 -*-
"""baseline_direct_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ja4hNzuYqY88mP2XugG37aJPoYYaB1K7

# Baseline Direct Translation Pipeline (Marian + NLLB)
### Honors Thesis – Fall 2025 Milestone  
Author: Jameela Kauser  
Goal: Implement direct translation baseline and evaluation protocol.

1. Install Dependencies
"""

!pip install transformers sentencepiece sacrebleu evaluate bert-score comet-ml pandas numpy tqdm gitpython

"""2. Imports & GPU setup"""

import torch
import pandas as pd
import numpy as np
from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
import sacrebleu
import evaluate
from bert_score import score as bertscore
from tqdm import tqdm
import os

device = "cuda" if torch.cuda.is_available() else "cpu"
device

"""3. Load Marian + NLLB"""

marian_translator = pipeline(
    "translation",
    model="Helsinki-NLP/opus-mt-en-fr"
)

nllb_model_name = "facebook/nllb-200-distilled-600M"

nllb_tokenizer = AutoTokenizer.from_pretrained(nllb_model_name)
nllb_model = AutoModelForSeq2SeqLM.from_pretrained(nllb_model_name).to(device)

def nllb_translate(text, tgt="fra_Latn"):
    inputs = nllb_tokenizer(text, return_tensors="pt").to(device)
    bos = nllb_tokenizer.convert_tokens_to_ids(tgt)
    output = nllb_model.generate(
        **inputs,
        forced_bos_token_id=bos
    )
    return nllb_tokenizer.decode(output[0], skip_special_tokens=True)

"""4. Run baseline translations"""

def run_translations(sentences, tgt_lang="fra_Latn", out_path="baseline_outputs.csv"):
    logs = []
    for s in tqdm(sentences):
        marian_out = marian_translator(s)[0]['translation_text']
        nllb_out = nllb_translate(s, tgt=tgt_lang)

        logs.append({
            "source": s,
            "marian_translation": marian_out,
            "nllb_translation": nllb_out
        })

    df = pd.DataFrame(logs)
    df.to_csv(out_path, index=False)
    return df

sentences = [
    "Knowledge is power.",
    "Education should be accessible to everyone.",
    "Language connects people.",
    "This is a test sentence for evaluation."
]

df = run_translations(sentences, tgt_lang="fra_Latn")
df

"""5. BLEU and BERTScore evaluation"""

def compute_bleu(hypotheses, references):
    return sacrebleu.corpus_bleu(hypotheses, [references]).score

def compute_bertscore(hypotheses, references, lang="fr"):
    _, _, F1 = bertscore(hypotheses, references, lang=lang)
    return float(F1.mean())

df["reference"] = df["nllb_translation"]  # Placeholder until real references

"""6. Run Evaluation on Both Models"""

marian_hyp = df["marian_translation"].tolist()
nllb_hyp = df["nllb_translation"].tolist()
ref = df["reference"].tolist()
src = df["source"].tolist()

results = {
    "BLEU_marian": compute_bleu(marian_hyp, ref),
    "BLEU_nllb": compute_bleu(nllb_hyp, ref),
    "BERT_marian": compute_bertscore(marian_hyp, ref),
    "BERT_nllb": compute_bertscore(nllb_hyp, ref)
}

results

"""7. Save Metrics to CSV"""

pd.DataFrame([results]).to_csv("baseline_metrics.csv", index=False)